import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import Header from "./components/header";


const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en" className='scroll-smooth'>
        <body className={`${figtree.className} dark text-foreground bg-background`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
      </html>

  );
}
